### PR TITLE
Rename projects

### PR DESCRIPTION
**Pull request by WKocur**
Renames projects to products through the site including db migrations. Renaming is the only work done, so you may want to check out the migrations but a very light skim over the rest of the code is probably all that is needed.

Project is retained only for naming in github sync controller (which was broken already anyway) and for Project code (e.g. deltek code).

Tests were already broken too - I'll deal with the merge conflicts between this and the test branch once this is merged 👍

### CODE REVIEW

**Review by defaye — CHANGES_REQUESTED** [review]
I get the following errors when trying to migrate.

The migrations don't run fully:

```
== 20141104161910 RenameRepositoryUrlColumnInProjects: migrated (0.0012s) =====

== 20141105144405 ChangeDataTypeForInternalClientsInProjects: migrating =======
-- add_column(:projects, :internal_clients, :text, {:array=>true, :default=>[]})
   -> 0.0066s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant ChangeDataTypeForInternalClientsInProjects::Project
/home/jono/Code/labs/db/migrate/20141105144405_change_data_type_for_internal_clients_in_projects.rb:5:in `change'

Caused by:
NameError: uninitialized constant ChangeDataTypeForInternalClientsInProjects::Project
/home/jono/Code/labs/db/migrate/20141105144405_change_data_type_for_internal_clients_in_projects.rb:5:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by defaye** [comment]
I've gone through all the files manually and checked the changes... I did not spot anything unusual. I have not been able to test anything locally as I don't have a complete `secrets.yml` for development I don't think.

**Comment by WKocur** [comment]
> I get the following errors when trying to migrate.
> 
> The migrations don't run fully:
> 
> ```
> == 20141104161910 RenameRepositoryUrlColumnInProjects: migrated (0.0012s) =====
> 
> == 20141105144405 ChangeDataTypeForInternalClientsInProjects: migrating =======
> -- add_column(:projects, :internal_clients, :text, {:array=>true, :default=>[]})
>    -> 0.0066s
> rake aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> uninitialized constant ChangeDataTypeForInternalClientsInProjects::Project
> /home/jono/Code/labs/db/migrate/20141105144405_change_data_type_for_internal_clients_in_projects.rb:5:in `change'
> 
> Caused by:
> NameError: uninitialized constant ChangeDataTypeForInternalClientsInProjects::Project
> /home/jono/Code/labs/db/migrate/20141105144405_change_data_type_for_internal_clients_in_projects.rb:5:in `change'
> Tasks: TOP => db:migrate
> (See full trace by running task with --trace)
> ```

Hmmm yes will need to think about how to handle this as the Project model no longer exists... What do you think is the best approach... Might just be a case of commenting out the Project code... anyone using the new version of the migration will no longer have the Project model and anyone who still has the Project model will not have the change in the migration (as they are on an older version)...

**Comment by defaye** [comment]
> Hmmm yes will need to think about how to handle this as the Project model no longer exists... What do you think is the best approach... Might just be a case of commenting out the Project code... anyone using the new version of the migration will no longer have the Project model and anyone who still has the Project model will not have the change in the migration (as they are on an older version)...

Are we able to just drop the entire database and rerun migrations?

**Comment by WKocur** [comment]
> > Hmmm yes will need to think about how to handle this as the Project model no longer exists... What do you think is the best approach... Might just be a case of commenting out the Project code... anyone using the new version of the migration will no longer have the Project model and anyone who still has the Project model will not have the change in the migration (as they are on an older version)...
> 
> Are we able to just drop the entire database and rerun migrations?

I think that's the instance when you'll get this error. I didn't get it because I'd already run that migration in the past. I guess the issue is that the migrations are dependent on the current code rather than database state, because of the use of 'Project'.

**Comment by WKocur** [comment]
This migration was 6 years ago, so no one has a db state from before the migration... So there should be no need to map the old 'internal_client' to new 'internal_clients'. Anyone new would be using a db dump and the rest of the migration will ensure the correct schema.

I reckon we can just comment it out and add a note explaining why. BUT perhaps that's a terrible idea. What do you think? Perhaps worth testing that it actually works if you comment it out...

**Comment by defaye** [comment]
> I reckon we can just comment it out and add a note explaining why. BUT perhaps that's a terrible idea. What do you think? Perhaps worth testing that it actually works if you comment it out...

It would seem like we don't have much of a choice but to edit the migrations in this way, putting in a dummy class for Project for e.g. doesn't make much sense either.

**Comment by WKocur** [comment]
> > I reckon we can just comment it out and add a note explaining why. BUT perhaps that's a terrible idea. What do you think? Perhaps worth testing that it actually works if you comment it out...
> 
> It would seem like we don't have much of a choice but to edit the migrations in this way, putting in a dummy class for Project for e.g. doesn't make much sense either.

I've made this change - could you see if the migrations now run for you? 🤞

**Pull request merged**
